TYPO3:
  Neos:
    typoScript:
      autoInclude:
        'Dotpulse.Button': TRUE

Dotpulse:
  Button:
    btnClass: btn
    bleedClass: btn-block
    largeClass: btn-lg
    marginClass: btn-margin
    externalTarget: _blank
    assetExternal: 'image,pdf'
